### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by parkervcp** [BoukeHaarsma23/WattmanGTK#27]
While attempting to run the application I get an index out of range error. I have a Sapphire Vega 64 on an asus strix Z370-E gaming motherboard.

I have output a lot of info below on my status for drivers and otherwise.

```
[parker@boromir WattmanGTK]$ python run.py 
1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
03:00.0 uses amdgpu kernel driver
Traceback (most recent call last):
  File "run.py", line 23, in <module>
    wattman.main()
  File "/home/parker/dev/WattmanGTK/WattmanGTK/wattman.py", line 97, in main
    sysfspath = str(Path(glob.glob("/sys/devices/*/*/*"+pci_id)[0]))
IndexError: list index out of range

[parker@boromir WattmanGTK]$ printf "0x%08x\n" $(cat /sys/module/amdgpu/parameters/ppfeaturemask)
0xffff7fff

[parker@boromir WattmanGTK]$ lspci | grep VGA
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Vega 10 XT [Radeon RX Vega 64] (rev c1)

[parker@boromir WattmanGTK]$ lsmod | grep "kms\|drm"
drm_kms_helper        200704  1 amdgpu
drm                   479232  9 gpu_sched,drm_kms_helper,amdgpu,ttm
agpgart                49152  2 ttm,drm
syscopyarea            16384  1 drm_kms_helper
sysfillrect            16384  1 drm_kms_helper
sysimgblt              16384  1 drm_kms_helper
fb_sys_fops            16384  1 drm_kms_helper

[parker@boromir WattmanGTK]$ find /dev -group video
/dev/fb0
/dev/dri/card0

[parker@boromir WattmanGTK]$ cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-linux root=UUID=ecea1b12-7154-4663-a941-dfb04a1a4a3b rw quiet resume=UUID=c9b2c33e-d3e1-4bd9-963e-3f0026014e10 amdgpu.dc=1 amdgpu.ppfeaturemask=0xffff7fff

[parker@boromir WattmanGTK]$ find /etc/modprobe.d/
/etc/modprobe.d/

[parker@boromir WattmanGTK]$ cat /etc/modprobe.d/*kms*
cat: '/etc/modprobe.d/*kms*': No such file or directory

[parker@boromir WattmanGTK]$ ls /etc/X11/xorg.conf
ls: cannot access '/etc/X11/xorg.conf': No such file or directory

[parker@boromir WattmanGTK]$ glxinfo | grep -i "vendor\|rendering"
direct rendering: Yes
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
    Vendor: X.Org (0x1002)
OpenGL vendor string: X.Org

[parker@boromir WattmanGTK]$ grep LoadModule /var/log/Xorg.0.log
[     4.250] (II) LoadModule: "glx"
[     4.258] (II) LoadModule: "ati"
[     4.258] (II) LoadModule: "modesetting"
[     4.260] (II) LoadModule: "fbdev"
[     4.260] (II) LoadModule: "vesa"
[     4.281] (II) LoadModule: "fbdevhw"
[     4.282] (II) LoadModule: "glamoregl"
[     4.518] (II) LoadModule: "fb"
[     4.619] (II) LoadModule: "libinput"
```

**Comment by parkervcp** [comment]
Done - https://gist.github.com/parkervcp/848832e4d667452320de6209b8ec724e

**Comment by BoukeHaarsma23** [comment]
Also, make sure you are using python3!
you can check by `python -V`
if this is a python2 version, run the script with python3

**Comment by parkervcp** [comment]
It's 3.7.1. I know better than that.

**Comment by BoukeHaarsma23** [comment]
Does e0160556a21f26e5fef200974b3c4a77891625ce fix this for you?

**Comment by BoukeHaarsma23** [comment]
You could also try to revert 664ffb3c418960640f8b883096bdeb22a9dd111c

**Comment by parkervcp** [comment]
That seems to have fixed it.

**Comment by BoukeHaarsma23** [comment]
@parkervcp please let me know if the AMDGPU-detection branch works for your system

**Comment by parkervcp** [comment]
I will test again after I get home this evening.

I spent quite a bit of time playing with settings and it appeared to be getting settings correctly after I ran the shell script to update settings.

**Comment by parkervcp** [comment]
Using that branch I still get 

```
[parker@boromir WattmanGTK]$ git branch
* AMDGPU-detection
[parker@boromir WattmanGTK]$ python run.py 
1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
03:00.0 uses amdgpu kernel driver
Searching for sysfs path...
Traceback (most recent call last):
  File "run.py", line 23, in <module>
    wattman.main()
  File "/home/parker/dev/WattmanGTK/WattmanGTK/wattman.py", line 99, in main
    sysfspath = str(Path(glob.glob("/sys/devices/pci0000:00/**/0000:"+pci_id)[0]))
IndexError: list index out of range
[parker@boromir WattmanGTK]$ 
```

**Comment by BoukeHaarsma23** [comment]
I pushed another way of checking cardpaths in the AMDGPU-detection branch. See commit 5e0b001fe41b8533638b4a459d0b6213caadc88d 

If you could test with this commit that would be appreciated

**Comment by parkervcp** [comment]
I have got to this now - 
```
[parker@boromir WattmanGTK]$ python run.py 
1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
03:00.0 uses amdgpu kernel driver
Searching for sysfs path...
Searching for GPU with string: /sys/devices/pci????:??/????:03:00.0
Searching for GPU with string: /sys/devices/pci????:??/**/????:03:00.0
Searching for GPU with string: /sys/devices/pci????:??/**/**/????:03:00.0
Searching for GPU with string: /sys/devices/pci????:??/**/**/**/????:03:00.0
Multiple sysfsmatches found!
Something went wrong in searching for the sysfspath
[parker@boromir WattmanGTK]$ 
```

Also per your request - https://gist.github.com/parkervcp/728c71c73d485e3d8bff25badb286f9e

**Comment by BoukeHaarsma23** [comment]
Thanks for the feedback. However I cannot see what multiple paths it did find at that point.

Could you maybe change in wattman.py (line 110)
`print("Multiple sysfsmatches found!")`
to 
`print(found)`

and rerun the program? I think that will give me some better insight into why the search with that string returned multiple values.

**Comment by BoukeHaarsma23** [comment]
Or we can just loop over all possibilities. See 3dd2e3f6f59882dc2fbf46cbe4fff7089a38d582

Please re-run and let me know

**Comment by parkervcp** [comment]
@BoukeHaarsma23 That looks to have worked. Wattman started and looks to have started correctly.

Output is as below.
```
[parker@boromir WattmanGTK]$ python run.py 
1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
03:00.0 uses amdgpu kernel driver
Searching for sysfs path...
Searching for GPU with string: /sys/devices/pci????:??/????:03:00.0
Searching for GPU with string: /sys/devices/pci????:??/**/????:03:00.0
Searching for GPU with string: /sys/devices/pci????:??/**/**/????:03:00.0
Searching for GPU with string: /sys/devices/pci????:??/**/**/**/????:03:00.0
Multiple sysfsmatches found! Checking which one will suffice...
Checking /sys/devices/pci0000:00/0000:00:17.0/subsystem/devices/0000:03:00.0 for pp_dpm_sclk file
Sysfs path found in /sys/devices/pci0000:00/0000:00:17.0/subsystem/devices/0000:03:00.0
amdgpu card found in /sys/class/hwmon/hwmon3 hwmon folder
```

**Comment by BoukeHaarsma23** [comment]
Ok great, in the future I will store the path somewhere so it does not have to search for the path everytime the application starts. I will close this for now.
