### ISSUE TITLE
TypeError: %d format: a number is required, not str (Kubuntu 18.10, RX 580)

### ISSUE THREAD

**Issue by kwahoo2** [BoukeHaarsma23/WattmanGTK#36]
Full console output:

```wattmanGTK
1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
22:00.0 uses amdgpu kernel driver
Searching for sysfs path...
/sys/devices/pci0000:00/0000:00:03.1/0000:22:00.0 belongs to 22:00.0 with symbolic link to /sys/class/drm/card0/device
Sysfs path found in /sys/devices/pci0000:00/0000:00:03.1/0000:22:00.0
amdgpu card found in /sys/class/hwmon/hwmon0 hwmon folder
Checking which device this hwmon path belongs to
/sys/class/hwmon/hwmon0 belongs to /sys/devices/pci0000:00/0000:00:03.1/0000:22:00.0 (Micro-Star International Co., Ltd. [MSI] Radeon RX 580 Armor 4G OC)
No fan control

(wattmanGTK:4853): Gtk-WARNING **: 21:28:05.273: Theme parsing error: gtk.css:127:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(wattmanGTK:4853): Gtk-WARNING **: 21:28:05.273: Theme parsing error: gtk.css:128:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(wattmanGTK:4853): Gtk-WARNING **: 21:28:05.273: Theme parsing error: gtk.css:132:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(wattmanGTK:4853): Gtk-WARNING **: 21:28:05.274: Theme parsing error: gtk.css:142:29: The style property GtkStatusbar:shadow-type is deprecated and shouldn't be used anymore. It will be removed in a future version
Traceback (most recent call last):
  File "/usr/local/bin/wattmanGTK", line 11, in <module>
    load_entry_point('WattmanGTK==0.0.1', 'console_scripts', 'wattmanGTK')()
  File "/usr/local/lib/python3.6/dist-packages/WattmanGTK-0.0.1-py3.6.egg/WattmanGTK/wattman.py", line 121, in main
    Handler0 = Handler(builder,GPUs)
  File "/usr/local/lib/python3.6/dist-packages/WattmanGTK-0.0.1-py3.6.egg/WattmanGTK/handler.py", line 43, in __init__
    self.update_gui()
  File "/usr/local/lib/python3.6/dist-packages/WattmanGTK-0.0.1-py3.6.egg/WattmanGTK/handler.py", line 216, in update_gui
    self.builder.get_object("Current FAN Speed").set_text("Current speed\n %d RPM" % self.GPU.fan_speed)
TypeError: %d format: a number is required, not str
```

**Comment by BoukeHaarsma23** [comment]
Let me know if this fixed it for you.

**Comment by kwahoo2** [comment]
Yes, it's fixed.
