### ISSUE TITLE
Cannot start with Sapphire R290 TriX OC / fan1_input

### ISSUE THREAD

**Issue by DonHugo69** [BoukeHaarsma23/WattmanGTK#37]
Hi, when I start to launch WattmanGTK via the terminal I end up with this output:

```
1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
01:00.0 uses amdgpu kernel driver
Searching for sysfs path...
/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0 belongs to 01:00.0 with symbolic link to /sys/class/drm/card0/device
Sysfs path found in /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0
amdgpu card found in /sys/class/hwmon/hwmon0 hwmon folder
Checking which device this hwmon path belongs to
/sys/class/hwmon/hwmon0 belongs to /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0 (PC Partner Limited / Sapphire Technology Hawaii PRO [Radeon R9 290/390])
Found sensor fan1_input
Trying to read /sys/class/hwmon/hwmon0/fan1_input
Traceback (most recent call last):
  File "/usr/bin/wattmanGTK", line 11, in <module>
    load_entry_point('WattmanGTK==0.0.1', 'console_scripts', 'wattmanGTK')()
  File "/usr/lib/python3.7/site-packages/WattmanGTK/wattman.py", line 115, in main
    card.sensors = card.init_sensors()
  File "/usr/lib/python3.7/site-packages/WattmanGTK/GPU.py", line 165, in init_sensors
    value = read(self.hwmonpath + path)
  File "/usr/lib/python3.7/site-packages/WattmanGTK/util.py", line 20, in read
    value = origin_file.readline()
OSError: [Errno 19] Kein passendes Gerät gefunden
```

OS: Arch Linux, 4.18 (Zen kernel), up to date at the time of writing

**Comment by BoukeHaarsma23** [comment]
Let me know if it works for you now.

**Comment by DonHugo69** [comment]
Unfortunately still the same error.
```
1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
01:00.0 uses amdgpu kernel driver
Searching for sysfs path...
/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0 belongs to 01:00.0 with symbolic link to /sys/class/drm/card0/device
Sysfs path found in /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0
amdgpu card found in /sys/class/hwmon/hwmon0 hwmon folder
Checking which device this hwmon path belongs to
/sys/class/hwmon/hwmon0 belongs to /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0 (PC Partner Limited / Sapphire Technology Hawaii PRO [Radeon R9 290/390])
Found sensor in0_input
Trying to read /sys/class/hwmon/hwmon0/in0_input
Traceback (most recent call last):
  File "/usr/bin/wattmanGTK", line 11, in <module>
    load_entry_point('WattmanGTK==0.0.1', 'console_scripts', 'wattmanGTK')()
  File "/usr/lib/python3.7/site-packages/WattmanGTK/wattman.py", line 113, in main
    card.sensors = card.init_sensors()
  File "/usr/lib/python3.7/site-packages/WattmanGTK/GPU.py", line 165, in init_sensors
    value = read(self.hwmonpath + path)
  File "/usr/lib/python3.7/site-packages/WattmanGTK/util.py", line 20, in read
    value = origin_file.readline()
OSError: [Errno 22] Das Argument ist ungültig
```

However, I think it is likely that my card is the one to blame here. When I use `sensors` I see several parameters which do not get read out properly
```
amdgpu-pci-0100
Adapter: PCI adapter
vddgfx:           N/A  
fan1:           0 RPM
temp1:        +67.0°C  (crit = +120.0°C, hyst = +90.0°C)
ERROR: Can't get value of subfeature power1_cap: Can't read
power1:           N/A  (cap =   0.00 W)
```
Maybe this card is not properly supported or even defunct.

**Comment by BoukeHaarsma23** [comment]
Yeah it is a bit strange though. Since the exception on line 28 on `util.py` should handle this.

You could maybe change line 28 on `util.py` 
from
`except:`
to
`except OSError:`
Since that is the exact error it throws. Let me know if that helps for you.

**Comment by BoukeHaarsma23** [comment]
The try statement was not around the file operation. ca6ff2b2085ee106219cb773bd2031fd9048a043 should fix this for you. Please let me know if it did.

**Comment by DonHugo69** [comment]
This looks better now, the non-working sensors are skipped. But now I encounter a new error 
```
1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
01:00.0 uses amdgpu kernel driver
Searching for sysfs path...
/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0 belongs to 01:00.0 with symbolic link to /sys/class/drm/card0/device
Sysfs path found in /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0
amdgpu card found in /sys/class/hwmon/hwmon0 hwmon folder
Checking which device this hwmon path belongs to
/sys/class/hwmon/hwmon0 belongs to /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0 (PC Partner Limited / Sapphire Technology Hawaii PRO [Radeon R9 290/390])
Found sensor in0_input
Trying to read /sys/class/hwmon/hwmon0/in0_input
Found sensor temp1_crit
Trying to read /sys/class/hwmon/hwmon0/temp1_crit
Found sensor pwm1_enable
Trying to read /sys/class/hwmon/hwmon0/pwm1_enable
Found sensor pwm1
Trying to read /sys/class/hwmon/hwmon0/pwm1
Found sensor temp1_crit_hyst
Trying to read /sys/class/hwmon/hwmon0/temp1_crit_hyst
Found sensor power1_cap_min
Trying to read /sys/class/hwmon/hwmon0/power1_cap_min
Found sensor power1_cap
Trying to read /sys/class/hwmon/hwmon0/power1_cap
Found sensor pwm1_min
Trying to read /sys/class/hwmon/hwmon0/pwm1_min
Found sensor power1_average
Trying to read /sys/class/hwmon/hwmon0/power1_average
Found sensor power1_cap_max
Trying to read /sys/class/hwmon/hwmon0/power1_cap_max
Found sensor fan1_input
Trying to read /sys/class/hwmon/hwmon0/fan1_input
Found sensor temp1_input
Trying to read /sys/class/hwmon/hwmon0/temp1_input
Found sensor pwm1_max
Trying to read /sys/class/hwmon/hwmon0/pwm1_max
Found sensor in0_label
Trying to read /sys/class/hwmon/hwmon0/in0_label
Cannot read file pp_od_clk_voltage, trying using pp_dpm_sclk and pp_dpm_mclk
Cannot do seperate overclocking via states, only by percentage!
No powercap sensors
No fan control
Traceback (most recent call last):
  File "/usr/bin/wattmanGTK", line 11, in <module>
    load_entry_point('WattmanGTK==0.0.1', 'console_scripts', 'wattmanGTK')()
  File "/usr/lib/python3.7/site-packages/WattmanGTK/wattman.py", line 141, in main
    Plot0 = Handler0.init_plot(0, maxpoints, precision, linux_kernelmain, linux_kernelsub)
  File "/usr/lib/python3.7/site-packages/WattmanGTK/handler.py", line 72, in init_plot
    self.plot = Plot(self.builder, self.GPUs, maxpoints, precision, linux_kernelmain, linux_kernelsub)
  File "/usr/lib/python3.7/site-packages/WattmanGTK/plot.py", line 70, in __init__
    self.update_signals()
  File "/usr/lib/python3.7/site-packages/WattmanGTK/plot.py", line 176, in update_signals
    self.signalstore[i][5]=str(np.around(convert_to_si(Plotsignal.unit, Plotsignal.get_min())[1], self.precision))
  File "/usr/lib/python3.7/site-packages/WattmanGTK/util.py", line 37, in convert_to_si
    return unit[0] + unit[2:], value / 1000
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

**Comment by DonHugo69** [comment]
And it works! Thanks a lot for your great support!
