### ISSUE TITLE
After latest commits program no longer runs

### ISSUE THREAD

**Issue by parkerlreed** [BoukeHaarsma23/WattmanGTK#38]
Arch
Linux stealth 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux
wattman-gtk-git r161.0347b9e-1

Last known good revision 6360fab

````

(wattmanGTK:18982): Gtk-WARNING **: 17:08:28.680: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(wattmanGTK:18982): Gtk-WARNING **: 17:08:28.680: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(wattmanGTK:18982): Gtk-WARNING **: 17:08:28.680: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
The overdrive functionality seems not enabled on this system.
This means WattmanGTK can not be used.
You could force it by flipping the overdrive bit. For this system it would mean to set amdgpu.ppfeaturemask=0xffff7fff
2 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
07:00.0 uses amdgpu kernel driver
Searching for sysfs path...
/sys/devices/pci0000:00/0000:00:1c.4/0000:02:00.0/0000:03:01.0/0000:05:00.0/0000:06:01.0/0000:07:00.0 belongs to 07:00.0 with symbolic link to /sys/class/drm/card1/device
Sysfs path found in /sys/devices/pci0000:00/0000:00:1c.4/0000:02:00.0/0000:03:01.0/0000:05:00.0/0000:06:01.0/0000:07:00.0
amdgpu card found in /sys/class/hwmon/hwmon3 hwmon folder
Checking which device this hwmon path belongs to
/sys/class/hwmon/hwmon3 belongs to /sys/devices/pci0000:00/0000:00:1c.4/0000:02:00.0/0000:03:01.0/0000:05:00.0/0000:06:01.0/0000:07:00.0 (XFX Pine Group Inc. Polaris 21 XL [Radeon RX 560D])
Found sensor in0_input
Trying to read /sys/class/hwmon/hwmon3/in0_input
Found sensor temp1_crit
Trying to read /sys/class/hwmon/hwmon3/temp1_crit
Found sensor pwm1_enable
Trying to read /sys/class/hwmon/hwmon3/pwm1_enable
Found sensor pwm1
Trying to read /sys/class/hwmon/hwmon3/pwm1
Found sensor temp1_crit_hyst
Trying to read /sys/class/hwmon/hwmon3/temp1_crit_hyst
Found sensor power1_cap_min
Trying to read /sys/class/hwmon/hwmon3/power1_cap_min
Found sensor power1_cap
Trying to read /sys/class/hwmon/hwmon3/power1_cap
Found sensor pwm1_min
Trying to read /sys/class/hwmon/hwmon3/pwm1_min
Found sensor power1_average
Trying to read /sys/class/hwmon/hwmon3/power1_average
Found sensor power1_cap_max
Trying to read /sys/class/hwmon/hwmon3/power1_cap_max
Found sensor fan1_input
Trying to read /sys/class/hwmon/hwmon3/fan1_input
Found sensor temp1_input
Trying to read /sys/class/hwmon/hwmon3/temp1_input
Found sensor pwm1_max
Trying to read /sys/class/hwmon/hwmon3/pwm1_max
Found sensor in0_label
Trying to read /sys/class/hwmon/hwmon3/in0_label
No fan control
Traceback (most recent call last):
  File "/usr/bin/wattmanGTK", line 11, in <module>
    load_entry_point('WattmanGTK==0.0.1', 'console_scripts', 'wattmanGTK')()
  File "/usr/lib/python3.7/site-packages/WattmanGTK/wattman.py", line 121, in main
    Handler0 = Handler(builder,GPUs)
  File "/usr/lib/python3.7/site-packages/WattmanGTK/handler.py", line 40, in __init__
    self.set_maximum_values()
  File "/usr/lib/python3.7/site-packages/WattmanGTK/handler.py", line 96, in set_maximum_values
    if not None in self.GPU.fan_target:
TypeError: argument of type 'NoneType' is not iterable
````

**Comment by BoukeHaarsma23** [comment]
Let me know if it works for you again.

**Comment by parkerlreed** [comment]
:+1: 
![2018-11-12_18-33](https://user-images.githubusercontent.com/841440/48381344-8466ef00-e6a9-11e8-8fc6-9f136b43fb64.png)

**Comment by BoukeHaarsma23** [comment]
@parkerlreed could you also help #39? Since I see you got it running on a KDE desktop
