### ISSUE TITLE
RX 540 gpu, does not launch

### ISSUE THREAD

**Issue by tuxutku** [BoukeHaarsma23/WattmanGTK#40]
```
[utku2@utku2 ~]$ wattmanGTK
1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
00:01.0 uses amdgpu kernel driver
Searching for sysfs path...
/sys/devices/pci0000:00/0000:00:01.0 belongs to 00:01.0 with symbolic link to /sys/class/drm/card0/device
Sysfs path found in /sys/devices/pci0000:00/0000:00:01.0
amdgpu card found in /sys/class/hwmon/hwmon4 hwmon folder
Checking which device this hwmon path belongs to
amdgpu card found in /sys/class/hwmon/hwmon3 hwmon folder
Checking which device this hwmon path belongs to
/sys/class/hwmon/hwmon3 belongs to /sys/devices/pci0000:00/0000:00:01.0 (Acer Incorporated [ALI] Wani [Radeon R5/R6/R7 Graphics])
Found sensor temp1_crit
Trying to read /sys/class/hwmon/hwmon3/temp1_crit
Found sensor pwm1_enable
Trying to read /sys/class/hwmon/hwmon3/pwm1_enable
Found sensor pwm1
Trying to read /sys/class/hwmon/hwmon3/pwm1
Found sensor temp1_crit_hyst
Trying to read /sys/class/hwmon/hwmon3/temp1_crit_hyst
Found sensor pwm1_min
Trying to read /sys/class/hwmon/hwmon3/pwm1_min
Found sensor fan1_input
Trying to read /sys/class/hwmon/hwmon3/fan1_input
Found sensor temp1_input
Trying to read /sys/class/hwmon/hwmon3/temp1_input
Found sensor pwm1_max
Trying to read /sys/class/hwmon/hwmon3/pwm1_max
Cannot read file pp_od_clk_voltage, trying using pp_dpm_sclk and pp_dpm_mclk
Cannot do seperate overclocking via states, only by percentage!
No powercap sensors
No fan control
Traceback (most recent call last):
  File "/usr/bin/wattmanGTK", line 11, in <module>
    load_entry_point('WattmanGTK==0.0.1', 'console_scripts', 'wattmanGTK')()
  File "/usr/lib/python3.7/site-packages/WattmanGTK/wattman.py", line 132, in main
    Handler0 = Handler(builder,GPUs)
  File "/usr/lib/python3.7/site-packages/WattmanGTK/handler.py", line 43, in __init__
    self.update_gui()
  File "/usr/lib/python3.7/site-packages/WattmanGTK/handler.py", line 214, in update_gui
    self.GPU.get_currents()
  File "/usr/lib/python3.7/site-packages/WattmanGTK/GPU.py", line 213, in get_currents
    self.mem_clock, self.mem_state = self.get_current_clock("/pp_dpm_mclk")
TypeError: cannot unpack non-iterable NoneType object
```
i have amd rx 540 dedicated gpu and amd carrizo mobile gpu

**Comment by BoukeHaarsma23** [comment]
Sounds a lot like #14. Did you try [this solution ?](https://github.com/BoukeHaarsma23/WattmanGTK/issues/14#issuecomment-435704696)

**Comment by tuxutku** [comment]
i didn't understand
do you mean i should do: ``sudo su -c "echo option>/sys/class/drm/card0/device/power_dpm_force_performance_level"`` ?
```
[utku2@utku2 Wakfu]$ cat /sys/class/drm/card0/device/power_dpm_force_performance_level
auto
[utku2@utku2 Wakfu]$ cat /sys/class/drm/card1/device/power_dpm_force_performance_level
off
```

**Comment by BoukeHaarsma23** [comment]
The newest commits should fix your issue. However, you will not have clock speed readings.

**Comment by tuxutku** [comment]
```
[utku2@utku2 Programlar]$ git clone --recursive https://github.com/BoukeHaarsma23/WattmanGTK.git
Cloning into 'WattmanGTK'...
remote: Enumerating objects: 137, done.
remote: Counting objects: 100% (137/137), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 699 (delta 86), reused 122 (delta 73), pack-reused 562
Receiving objects: 100% (699/699), 577.25 KiB | 1.21 MiB/s, done.
Resolving deltas: 100% (452/452), done.
[utku2@utku2 Programlar]$ cd WattmanGTK
[utku2@utku2 WattmanGTK]$ ls
LICENSE  README.md  run.py  setup.py  WattmanGTK
[utku2@utku2 WattmanGTK]$ sudo python3 setup.py install
[sudo] password for utku2: 
running install
running bdist_egg
running egg_info
creating WattmanGTK.egg-info
writing WattmanGTK.egg-info/PKG-INFO
writing dependency_links to WattmanGTK.egg-info/dependency_links.txt
writing entry points to WattmanGTK.egg-info/entry_points.txt
writing requirements to WattmanGTK.egg-info/requires.txt
writing top-level names to WattmanGTK.egg-info/top_level.txt
writing manifest file 'WattmanGTK.egg-info/SOURCES.txt'
reading manifest file 'WattmanGTK.egg-info/SOURCES.txt'
writing manifest file 'WattmanGTK.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/WattmanGTK
copying WattmanGTK/util.py -> build/lib/WattmanGTK
copying WattmanGTK/handler.py -> build/lib/WattmanGTK
copying WattmanGTK/plot.py -> build/lib/WattmanGTK
copying WattmanGTK/plotsignal.py -> build/lib/WattmanGTK
copying WattmanGTK/__init__.py -> build/lib/WattmanGTK
copying WattmanGTK/GPU.py -> build/lib/WattmanGTK
copying WattmanGTK/wattman.py -> build/lib/WattmanGTK
creating build/lib/WattmanGTK/data
copying WattmanGTK/data/wattman.ui -> build/lib/WattmanGTK/data
copying WattmanGTK/data/WattmanGTK.eps -> build/lib/WattmanGTK/data
copying WattmanGTK/data/WattmanGTK.svg -> build/lib/WattmanGTK/data
copying WattmanGTK/data/WattmanGTK-outline-type.svg -> build/lib/WattmanGTK/data
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/WattmanGTK
copying build/lib/WattmanGTK/util.py -> build/bdist.linux-x86_64/egg/WattmanGTK
copying build/lib/WattmanGTK/handler.py -> build/bdist.linux-x86_64/egg/WattmanGTK
copying build/lib/WattmanGTK/plot.py -> build/bdist.linux-x86_64/egg/WattmanGTK
copying build/lib/WattmanGTK/plotsignal.py -> build/bdist.linux-x86_64/egg/WattmanGTK
copying build/lib/WattmanGTK/__init__.py -> build/bdist.linux-x86_64/egg/WattmanGTK
copying build/lib/WattmanGTK/GPU.py -> build/bdist.linux-x86_64/egg/WattmanGTK
creating build/bdist.linux-x86_64/egg/WattmanGTK/data
copying build/lib/WattmanGTK/data/WattmanGTK.eps -> build/bdist.linux-x86_64/egg/WattmanGTK/data
copying build/lib/WattmanGTK/data/WattmanGTK.svg -> build/bdist.linux-x86_64/egg/WattmanGTK/data
copying build/lib/WattmanGTK/data/wattman.ui -> build/bdist.linux-x86_64/egg/WattmanGTK/data
copying build/lib/WattmanGTK/data/WattmanGTK-outline-type.svg -> build/bdist.linux-x86_64/egg/WattmanGTK/data
copying build/lib/WattmanGTK/wattman.py -> build/bdist.linux-x86_64/egg/WattmanGTK
byte-compiling build/bdist.linux-x86_64/egg/WattmanGTK/util.py to util.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/WattmanGTK/handler.py to handler.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/WattmanGTK/plot.py to plot.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/WattmanGTK/plotsignal.py to plotsignal.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/WattmanGTK/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/WattmanGTK/GPU.py to GPU.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/WattmanGTK/wattman.py to wattman.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying WattmanGTK.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying WattmanGTK.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying WattmanGTK.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying WattmanGTK.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying WattmanGTK.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying WattmanGTK.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
WattmanGTK.__pycache__.wattman.cpython-37: module references __file__
creating dist
creating 'dist/WattmanGTK-0.0.1-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing WattmanGTK-0.0.1-py3.7.egg
creating /usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg
Extracting WattmanGTK-0.0.1-py3.7.egg to /usr/lib/python3.7/site-packages
Adding WattmanGTK 0.0.1 to easy-install.pth file
Installing wattmanGTK script to /usr/bin

Installed /usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg
Processing dependencies for WattmanGTK==0.0.1
Searching for pycairo==1.17.0
Best match: pycairo 1.17.0
Adding pycairo 1.17.0 to easy-install.pth file

Using /usr/lib/python3.7/site-packages
Searching for matplotlib==3.0.1
Best match: matplotlib 3.0.1
Adding matplotlib 3.0.1 to easy-install.pth file

Using /usr/lib/python3.7/site-packages
Searching for PyGObject==3.30.1
Best match: PyGObject 3.30.1
Adding PyGObject 3.30.1 to easy-install.pth file

Using /usr/lib/python3.7/site-packages
Searching for python-dateutil==2.7.5
Best match: python-dateutil 2.7.5
Adding python-dateutil 2.7.5 to easy-install.pth file

Using /usr/lib/python3.7/site-packages
Searching for pyparsing==2.3.0
Best match: pyparsing 2.3.0
Adding pyparsing 2.3.0 to easy-install.pth file

Using /usr/lib/python3.7/site-packages
Searching for kiwisolver==1.0.1
Best match: kiwisolver 1.0.1
Adding kiwisolver 1.0.1 to easy-install.pth file

Using /usr/lib/python3.7/site-packages
Searching for cycler==0.10.0
Best match: cycler 0.10.0
Adding cycler 0.10.0 to easy-install.pth file

Using /usr/lib/python3.7/site-packages
Searching for numpy==1.15.4
Best match: numpy 1.15.4
Adding numpy 1.15.4 to easy-install.pth file

Using /usr/lib/python3.7/site-packages
Searching for six==1.10.0
Best match: six 1.10.0
Adding six 1.10.0 to easy-install.pth file

Using /usr/lib/python3.7/site-packages
Searching for setuptools==40.5.0
Best match: setuptools 40.5.0
Adding setuptools 40.5.0 to easy-install.pth file
Installing easy_install script to /usr/bin
Installing easy_install-3.7 script to /usr/bin

Using /usr/lib/python3.7/site-packages
Finished processing dependencies for WattmanGTK==0.0.1
[utku2@utku2 WattmanGTK]$ wattmanGTK
1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
00:01.0 uses amdgpu kernel driver
Searching for sysfs path...
/sys/devices/pci0000:00/0000:00:01.0 belongs to 00:01.0 with symbolic link to /sys/class/drm/card0/device
Sysfs path found in /sys/devices/pci0000:00/0000:00:01.0
amdgpu card found in /sys/class/hwmon/hwmon4 hwmon folder
Checking which device this hwmon path belongs to
amdgpu card found in /sys/class/hwmon/hwmon3 hwmon folder
Checking which device this hwmon path belongs to
/sys/class/hwmon/hwmon3 belongs to /sys/devices/pci0000:00/0000:00:01.0 (Acer Incorporated [ALI] Wani [Radeon R5/R6/R7 Graphics])
Found sensor temp1_crit
Trying to read /sys/class/hwmon/hwmon3/temp1_crit
Found sensor pwm1_enable
Trying to read /sys/class/hwmon/hwmon3/pwm1_enable
Found sensor pwm1
Trying to read /sys/class/hwmon/hwmon3/pwm1
Found sensor temp1_crit_hyst
Trying to read /sys/class/hwmon/hwmon3/temp1_crit_hyst
Found sensor pwm1_min
Trying to read /sys/class/hwmon/hwmon3/pwm1_min
Found sensor fan1_input
Trying to read /sys/class/hwmon/hwmon3/fan1_input
Cannot read /sys/class/hwmon/hwmon3/fan1_input
Found sensor temp1_input
Trying to read /sys/class/hwmon/hwmon3/temp1_input
Found sensor pwm1_max
Trying to read /sys/class/hwmon/hwmon3/pwm1_max
Reading clock states and limits.
Cannot read file pp_od_clk_voltage, trying using pp_dpm_sclk and pp_dpm_mclk
Cannot do seperate overclocking via states, only by percentage!
Also got an error reading /sys/devices/pci0000:00/0000:00:01.0/pp_dpm_sclk or /sys/devices/pci0000:00/0000:00:01.0/pp_dpm_sclk
WattmanGTK will not be able to continue
[utku2@utku2 WattmanGTK]$ pkexec wattmanGTK
Unable to init server: Could not connect: Connection refused
Unable to init server: Bağlanılamadı: Connection refused

(wattmanGTK:4642): Gdk-CRITICAL **: 17:32:49.882: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/matplotlib/backends/backend_gtk3.py", line 28, in <module>
    cursors.MOVE          : Gdk.Cursor.new(Gdk.CursorType.FLEUR),
TypeError: constructor returned NULL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/wattmanGTK", line 11, in <module>
    load_entry_point('WattmanGTK==0.0.1', 'console_scripts', 'wattmanGTK')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2725, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2343, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2349, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/wattman.py", line 15, in <module>
    from WattmanGTK.handler import Handler # handles GUI
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/handler.py", line 22, in <module>
    from WattmanGTK.plot import Plot
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/plot.py", line 20, in <module>
    from matplotlib.backends.backend_gtk3cairo import FigureCanvasGTK3Cairo as FigureCanvas # required for GTK3 integration
  File "/usr/lib/python3.7/site-packages/matplotlib/backends/backend_gtk3cairo.py", line 1, in <module>
    from . import backend_cairo, backend_gtk3
  File "/usr/lib/python3.7/site-packages/matplotlib/backends/backend_gtk3.py", line 37, in <module>
    raise ImportError(exc)
ImportError: constructor returned NULL
[utku2@utku2 WattmanGTK]$ sudo wattmanGTK
1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
00:01.0 uses amdgpu kernel driver
Searching for sysfs path...
/sys/devices/pci0000:00/0000:00:01.0 belongs to 00:01.0 with symbolic link to /sys/class/drm/card0/device
Sysfs path found in /sys/devices/pci0000:00/0000:00:01.0
amdgpu card found in /sys/class/hwmon/hwmon4 hwmon folder
Checking which device this hwmon path belongs to
amdgpu card found in /sys/class/hwmon/hwmon3 hwmon folder
Checking which device this hwmon path belongs to
/sys/class/hwmon/hwmon3 belongs to /sys/devices/pci0000:00/0000:00:01.0 (Acer Incorporated [ALI] Wani [Radeon R5/R6/R7 Graphics])
Found sensor temp1_crit
Trying to read /sys/class/hwmon/hwmon3/temp1_crit
Found sensor pwm1_enable
Trying to read /sys/class/hwmon/hwmon3/pwm1_enable
Found sensor pwm1
Trying to read /sys/class/hwmon/hwmon3/pwm1
Found sensor temp1_crit_hyst
Trying to read /sys/class/hwmon/hwmon3/temp1_crit_hyst
Found sensor pwm1_min
Trying to read /sys/class/hwmon/hwmon3/pwm1_min
Found sensor fan1_input
Trying to read /sys/class/hwmon/hwmon3/fan1_input
Cannot read /sys/class/hwmon/hwmon3/fan1_input
Found sensor temp1_input
Trying to read /sys/class/hwmon/hwmon3/temp1_input
Found sensor pwm1_max
Trying to read /sys/class/hwmon/hwmon3/pwm1_max
Reading clock states and limits.
Cannot read file pp_od_clk_voltage, trying using pp_dpm_sclk and pp_dpm_mclk
Cannot do seperate overclocking via states, only by percentage!
Also got an error reading /sys/devices/pci0000:00/0000:00:01.0/pp_dpm_sclk or /sys/devices/pci0000:00/0000:00:01.0/pp_dpm_sclk
WattmanGTK will not be able to continue
```

**Comment by BoukeHaarsma23** [comment]
yeah this is similar to #13 
Your hardware does not seem to expose any powerplay features.

There is not much I can do to resolve this, therefore I am closing this.

**Comment by Haxk20** [comment]
> yeah this is similar to #13
> Your hardware does not seem to expose any powerplay features.
> 
> There is not much I can do to resolve this, therefore I am closing this.

4.20rc2 fixed the clock bug for me. Now gpu changes clocks normally.
