### ISSUE TITLE
Wattman finds video card, fails to launch

### ISSUE THREAD

**Issue by NHOrus** [BoukeHaarsma23/WattmanGTK#46]
```
python3 run.py                                                              
1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
amdgpu card found in /sys/class/hwmon/hwmon1 hwmon folder
Checking which device this hwmon path belongs to
Traceback (most recent call last):
  File "run.py", line 23, in <module>
    wattman.main()
  File "/home/nho/workshop/WattmanGTK/WattmanGTK/wattman.py", line 155, in main
    Handler0 = Handler(builder,GPUs)
  File "/home/nho/workshop/WattmanGTK/WattmanGTK/handler.py", line 38, in __init__
    self.GPU = GPUs[0]
IndexError: list index out of range
```

Card recognized as:
01:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Sun XT [Radeon HD 8670A/8670M/8690M / R5 M330 / M430 / R7 M520] (rev 83)

P.S. if amdgpu is compiled as a module, the feature flag can be set without messing with bootloader, but instead putting the line `options amdgpu ppfeaturemask=0xfffd7fff`  into `/etc/modprobe.d/local.conf` or equivalent file, then rebooting.

**Comment by BoukeHaarsma23** [comment]
That is strange, something is not executing properly in search if the sysfs path.
So the for loop which starts on line 110 in wattman.py

e.g. for my PC the output is something like

```
1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
23:00.0 uses amdgpu kernel driver
Searching for sysfs path...
/sys/devices/pci0000:00/0000:00:03.1/0000:23:00.0 belongs to 23:00.0 with symbolic link to /sys/class/drm/card0/device
Sysfs path found in /sys/devices/pci0000:00/0000:00:03.1/0000:23:00.0
amdgpu card found in /sys/class/hwmon/hwmon0 hwmon folder
Checking which device this hwmon path belongs to
/sys/class/hwmon/hwmon0 belongs to /sys/devices/pci0000:00/0000:00:03.1/0000:23:00.0 (ASUSTeK Computer Inc. Radeon RX 480 8GB)
```
Can you post your output of:
`lspci | grep -E "^.*VGA.*[AMD/ATI].*$" | grep -Eo "^([0-9a-fA-F]+:[0-9a-fA-F]+.[0-9a-fA-F])"`

**Comment by BoukeHaarsma23** [comment]
```e.g. for my PC the output is something like1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.23:00.0 uses amdgpu kernel driverSearching for sysfs path.../sys/devices/pci0000:00/0000:00:03.1/0000:23:00.0 belongs to 23:00.0 with symbolic link to /sys/class/drm/card0/deviceSysfs path found in /sys/devices/pci0000:00/0000:00:03.1/0000:23:00.0amdgpu card found in /sys/class/hwmon/hwmon0 hwmon folderChecking which device this hwmon path belongs to/sys/class/hwmon/hwmon0 belongs to /sys/devices/pci0000:00/0000:00:03.1/0000:23:00.0 (ASUSTeK Computer Inc. Radeon RX 480 8GB)```

**Comment by NHOrus** [comment]
lspci | grep -E "^.*VGA.*[AMD/ATI].*$" | grep -Eo "^([0-9a-fA-F]+:[0-9a-fA-F]+.[0-9a-fA-F])"
`00:02.0`
I'm on laptop with intel integrated card and discrete radeon videocard.

Relevant lines from lspci:

`00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)`
`01:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Sun XT [Radeon HD 8670A/8670M/8690M / R5 M330 / M430 / R7 M520] (rev 83)`


From `lshw`:
```
        *-display
             description: VGA compatible controller
             product: HD Graphics 620
             vendor: Intel Corporation
             physical id: 2
             bus info: pci@0000:00:02.0
             version: 02
             width: 64 bits
             clock: 33MHz
             capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
             configuration: driver=i915 latency=0
             resources: irq:126 memory:d0000000-d0ffffff memory:c0000000-cfffffff ioport:f000(size=64) memory:c0000-dffff
```
and
```
           *-display
                description: Display controller
                product: Sun XT [Radeon HD 8670A/8670M/8690M / R5 M330 / M430 / R7 M520]
                vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                physical id: 0
                bus info: pci@0000:01:00.0
                version: 83
                width: 64 bits
                clock: 33MHz
                capabilities: pm pciexpress msi bus_master cap_list rom
                configuration: driver=amdgpu latency=0
                resources: irq:129 memory:b0000000-bfffffff memory:d1200000-d123ffff ioport:e000(size=256) memory:d1240000-d125ffff
```

**Comment by BoukeHaarsma23** [comment]
ok, and what is the output of:
`lspci -k -s 00:02.0`

**Comment by NHOrus** [comment]
lspci -k -s 00:02.0
```
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)
	Subsystem: Lenovo HD Graphics 620
	Kernel driver in use: i915
	Kernel modules: i915
```

**Comment by BoukeHaarsma23** [comment]
> lspci | grep -E "^.VGA.[AMD/ATI].*$" | grep -Eo "^([0-9a-fA-F]+:[0-9a-fA-F]+.[0-9a-fA-F])"
> 00:02.0

Oh that is for your intel card I see. Then something is wrong there.

Can you post the full `lspci` output ? Something went wrong with processing that

**Comment by NHOrus** [comment]
```
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers (rev 02)
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)
00:14.0 USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller (rev 21)
00:14.2 Signal processing controller: Intel Corporation Sunrise Point-LP Thermal subsystem (rev 21)
00:16.0 Communication controller: Intel Corporation Sunrise Point-LP CSME HECI #1 (rev 21)
00:17.0 SATA controller: Intel Corporation Sunrise Point-LP SATA Controller [AHCI mode] (rev 21)
00:1c.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #1 (rev f1)
00:1c.4 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #5 (rev f1)
00:1c.5 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #6 (rev f1)
00:1f.0 ISA bridge: Intel Corporation Sunrise Point-LP LPC Controller (rev 21)
00:1f.2 Memory controller: Intel Corporation Sunrise Point-LP PMC (rev 21)
00:1f.3 Audio device: Intel Corporation Sunrise Point-LP HD Audio (rev 21)
00:1f.4 SMBus: Intel Corporation Sunrise Point-LP SMBus (rev 21)
01:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Sun XT [Radeon HD 8670A/8670M/8690M / R5 M330 / M430 / R7 M520] (rev 83)
02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)
03:00.0 Network controller: Intel Corporation Dual Band Wireless-AC 3165 Plus Bluetooth (rev 99)
```

**Comment by BoukeHaarsma23** [comment]
Thanks, will work on a fix now ;)

**Comment by NHOrus** [comment]
```
1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
01:00.0 uses amdgpu kernel driver
Searching for sysfs path...
/sys/devices/pci0000:00/0000:00:1c.0/0000:01:00.0 belongs to 01:00.0 with symbolic link to /sys/class/drm/card1/device
Sysfs path found in /sys/devices/pci0000:00/0000:00:1c.0/0000:01:00.0
amdgpu card found in /sys/class/hwmon/hwmon1 hwmon folder
Checking which device this hwmon path belongs to
/sys/class/hwmon/hwmon1 belongs to /sys/devices/pci0000:00/0000:00:1c.0/0000:01:00.0 (Lenovo Radeon R5 M430)
Found sensor in0_input
Trying to read /sys/class/hwmon/hwmon1/in0_input
Cannot read /sys/class/hwmon/hwmon1/in0_input
Found sensor temp1_crit
Trying to read /sys/class/hwmon/hwmon1/temp1_crit
Found sensor pwm1_enable
Trying to read /sys/class/hwmon/hwmon1/pwm1_enable
Found sensor pwm1
Trying to read /sys/class/hwmon/hwmon1/pwm1
Found sensor temp1_crit_hyst
Trying to read /sys/class/hwmon/hwmon1/temp1_crit_hyst
Found sensor power1_cap_min
Trying to read /sys/class/hwmon/hwmon1/power1_cap_min
Found sensor power1_cap
Trying to read /sys/class/hwmon/hwmon1/power1_cap
Found sensor pwm1_min
Trying to read /sys/class/hwmon/hwmon1/pwm1_min
Found sensor power1_average
Trying to read /sys/class/hwmon/hwmon1/power1_average
Cannot read /sys/class/hwmon/hwmon1/power1_average
Found sensor power1_cap_max
Trying to read /sys/class/hwmon/hwmon1/power1_cap_max
Found sensor fan1_input
Trying to read /sys/class/hwmon/hwmon1/fan1_input
Found sensor temp1_input
Trying to read /sys/class/hwmon/hwmon1/temp1_input
Found sensor pwm1_max
Trying to read /sys/class/hwmon/hwmon1/pwm1_max
Found sensor in0_label
Trying to read /sys/class/hwmon/hwmon1/in0_label
Reading clock states and limits.
Cannot read file pp_od_clk_voltage, trying using pp_dpm_sclk and pp_dpm_mclk
Cannot do seperate overclocking via states, only by percentage!
Also got an error reading /sys/devices/pci0000:00/0000:00:1c.0/0000:01:00.0/pp_dpm_sclk or /sys/devices/pci0000:00/0000:00:1c.0/0000:01:00.0/pp_dpm_sclk
WattmanGTK will not be able to continue
```

I think it's a problem of a card that's more supported by radeon-si driver than by amdgpu one.

**Comment by BoukeHaarsma23** [comment]
Yeah closing this, similar to #13 and #40 sadly

**Comment by NHOrus** [comment]
My video card lives in `/sys/devices/pci0000:00/0000:00:1c.0/0000:01:00.0/` : 
```
aer_dev_correctable   consistent_dma_mask_bits  driver_override   i2c-11  irq             msi_irqs                           pp_dpm_pcie            pp_sclk_od  resource0_wc      subsystem_vendor
aer_dev_fatal         current_link_speed        drm               i2c-12  local_cpulist   numa_node                          pp_dpm_sclk            pp_table    resource2         uevent
aer_dev_nonfatal      current_link_width        enable            i2c-13  local_cpus      power                              pp_force_state         remove      resource4         vbios_version
ari_enabled           d3cold_allowed            firmware_node     i2c-6   max_link_speed  power_dpm_force_performance_level  pp_mclk_od             rescan      revision          vendor
broken_parity_status  device                    gpu_busy_percent  i2c-7   max_link_width  power_dpm_state                    pp_num_states          reset       rom
class                 dma_mask_bits             hwmon             i2c-8   modalias        pp_cur_state                       pp_od_clk_voltage      resource    subsystem
config                driver                    i2c-10            i2c-9   msi_bus         pp_dpm_mclk                        pp_power_profile_mode  resource0   subsystem_device
```

**Comment by BoukeHaarsma23** [comment]
Just to confirm: what does 

`cat /sys/devices/pci0000:00/0000:00:1c.0/0000:01:00.0/pp_od_clk_voltage` say?
if emtpy:
what does:

`cat /sys/devices/pci0000:00/0000:00:1c.0/0000:01:00.0/pp_mclk_od`
say?

**Comment by NHOrus** [comment]
Maybe put error message that video card doesn't support powerplay features...

```
cat /sys/devices/pci0000:00/0000:00:1c.0/0000:01:00.0/pp_mclk_od
0
```

**Comment by BoukeHaarsma23** [comment]
sorry, I meant:
`cat /sys/devices/pci0000:00/0000:00:1c.0/0000:01:00.0/pp_dpm_sclk`

**Comment by NHOrus** [comment]
Empty.

**Comment by BoukeHaarsma23** [comment]
Yeah then I would recommend the radeon profile project:
https://github.com/marazmista/radeon-profile

**Comment by axipher** [comment]
What laptop model @NHOrus ?  I have a feeling that it is using some sort of hybrid graphics between the Intel HD 620 and the AMD 520 GPU (soemthing like the 15-bs576tx) where the iGPU is still active for 2d graphics loads, or for QuickSync usage.

The AMD graphics portion is probably rather limited and tied heavily to the chipset or just very limited in sensors and abilities.

@NHOrus have you tried running the Windows version of Wattman or AMD Overdrive?  Does it allow you to change any GPU settings?

**Comment by NHOrus** [comment]
Lenovo V310 and no.

**Comment by concatime** [comment]
I also have the same issue.
```
Cannot read file pp_od_clk_voltage, trying using pp_dpm_sclk and pp_dpm_mclk
Cannot do seperate overclocking via states, only by percentage!
Also got an error reading /sys/devices/pci0000:00/0000:00:02.1/0000:01:00.0/pp_dpm_sclk or /sys/devices/pci0000:00/0000:00:02.1/0000:01:00.0/pp_dpm_sclk
```
```
$ find /sys/devices/pci0000:00/ -name pp_dpm_sclk
/sys/devices/pci0000:00/0000:00:01.0/pp_dpm_sclk
/sys/devices/pci0000:00/0000:00:02.1/0000:01:00.0/pp_dpm_sclk
$ cat /sys/devices/pci0000:00/0000:00:01.0/pp_dpm_sclk
0: 200Mhz *
1: 300Mhz
2: 400Mhz
3: 496Mhz
4: 600Mhz
5: 685Mhz
6: 757Mhz
7: 847Mhz
$ cat /sys/devices/pci0000:00/0000:00:02.1/0000:01:00.0/pp_dpm_sclk
*EMPTY*
$ find /sys/devices/pci0000:00/ -name pp_dpm_mclk
/sys/devices/pci0000:00/0000:00:01.0/pp_dpm_mclk
/sys/devices/pci0000:00/0000:00:02.1/0000:01:00.0/pp_dpm_mclk
$ cat /sys/devices/pci0000:00/0000:00:01.0/pp_dpm_mclk
0: 667Mhz *
1: 800Mhz
$ cat /sys/devices/pci0000:00/0000:00:02.1/0000:01:00.0/pp_dpm_mclk
*EMPTY*
```
