### ISSUE TITLE
Cannot launch on Radeon VII

### ISSUE THREAD

**Issue by viggy96** [BoukeHaarsma23/WattmanGTK#58]
I get the following error when trying to launch the programme:

```
Reading clock states and limits.
Traceback (most recent call last):
  File "run.py", line 23, in <module>
    wattman.main()
  File "/home/vignesh/Downloads/WattmanGTK/WattmanGTK/wattman.py", line 151, in main
    card.get_states()
  File "/home/vignesh/Downloads/WattmanGTK/WattmanGTK/GPU.py", line 70, in get_states
    self.pstate_clock.append(int(match.group(2)))
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by erdalpekel** [comment]
I have the same problem.
I'm running Ubuntu 18.04.1 with driver version 18.50.

**Comment by fractalyse** [comment]
Same here with rx580

**Comment by Alexmitter** [comment]
Same with Radeon VII on Xubuntu 18.04, 4.20.13 Kernel, and Padoka Unstable PPA

**Comment by 2m** [comment]
Same here with 5.0.0 kernel. Can we help you somehow to implement this? Here is the contents of `pp_od_clk_voltage` of Radeon VII:

```
OD_SCLK:
0:        808Mhz
1:       1801Mhz
OD_MCLK:
1:       1000Mhz
OD_VDDC_CURVE:
0:        808Mhz        706mV
1:       1304Mhz        782mV
2:       1801Mhz       1084mV
OD_RANGE:
SCLK:     808Mhz       2200Mhz
MCLK:     351Mhz       1200Mhz
VDDC_CURVE_SCLK[0]:     808Mhz       2200Mhz
VDDC_CURVE_VOLT[0]:     738mV        1218mV
VDDC_CURVE_SCLK[1]:     808Mhz       2200Mhz
VDDC_CURVE_VOLT[1]:     738mV        1218mV
VDDC_CURVE_SCLK[2]:     808Mhz       2200Mhz
VDDC_CURVE_VOLT[2]:     738mV        1218mV
```

**Comment by jcfrosty** [comment]
Same issue here! Sabayon Linux kernel 5.0.15

**Comment by lwilletts** [comment]
Same here.

**Comment by kbeckmann** [comment]
A quick hack to make it sort of work:

´´´
diff --git a/WattmanGTK/GPU.py b/WattmanGTK/GPU.py
index 2286892..f2b17e2 100644
--- a/WattmanGTK/GPU.py
+++ b/WattmanGTK/GPU.py
@@ -45,8 +45,9 @@ class GPU:
         # Source https://cgit.freedesktop.org/~agd5f/linux/tree/drivers/gpu/drm/amd/amdgpu/amdgpu_pm.c?h=amd-staging-drm-next
         filepath = self.cardpath + "/pp_od_clk_voltage"
         label_pattern = r"^([a-zA-Z_]{1,}):$"
-        clock_limit_pattern = r"^(\d|\S{1,}):\s{1,}(\d{1,})(MHz|Mhz|mV)\s{1,}(\d{1,})(MHz|Mhz|mV)$"
-        print("Reading clock states and limits.")
+        clock_limit_pattern = r"^(\d|\S{1,}):\s{1,}(\d{1,})(MHz|Mhz)$"
+        label_value_value_pattern = r"^([^\s]+):\s{1,}(\d{1,})(MHz|Mhz|mV)\s{1,}(\d{1,})(MHz|Mhz|mV)$"
+        print("Reading clock states and limits from {}.".format(filepath))
         try:
             with open(filepath) as pp_od_clk_voltage:
                 # File not that large, can put all in memory
@@ -68,7 +69,7 @@ class GPU:
                         readingSCLK = False
                     match = re.match(clock_limit_pattern, line)
                     self.pstate_clock.append(int(match.group(2)))
-                    self.pstate_voltage.append(int(match.group(4)))
+                    self.pstate_voltage.append(0)
                 elif "OD_MCLK" in line or readingMCLK:
                     # Read Memory clocks
                     if not readingMCLK:
@@ -78,7 +79,7 @@ class GPU:
                         readingMCLK = False
                     match = re.match(clock_limit_pattern, line)
                     self.pmem_clock.append(int(match.group(2)))
-                    self.pmem_voltage.append(int(match.group(4)))
+                    self.pmem_voltage.append(0)
                 elif "OD_VDDC_CURVE" in line or readingVDDC:
                     print("Full VEGA20 support not implemented yet")
                     if not readingVDDC:
@@ -90,7 +91,7 @@ class GPU:
                     if not readingRANGE:
                         readingRANGE = True
                         continue
-                    match = re.match(clock_limit_pattern,line)
+                    match = re.match(label_value_value_pattern,line)
                     if match is None or labelmatch:
                         readingRANGE = False
                     if "SCLK" in match.group(1):
```

**Comment by kbeckmann** [comment]
Here's a quick and dirty patch that makes it work for radeon vii. It most likely breaks with other cards, I guess the format was changed.

https://github.com/kbeckmann/WattmanGTK/commit/6ad881e3eccd3164895c7565b062e5e0dfce8950

**Comment by gsedej** [comment]
edit: @kbeckmann, your patch work for me (app starts, but i didn't investigate much further)

It's also broken for me
Radeon 5700 xt
Kernel 5.6 RC1, ubuntu 18.04

```
...
Trying to read /sys/class/hwmon/hwmon2/temp2_input
Reading clock states and limits.
Traceback (most recent call last):
  File "run.py", line 23, in <module>
    wattman.main()
  File "/home/gasper/git/WattmanGTK/WattmanGTK/wattman.py", line 158, in main
    card.get_states()
  File "/home/gasper/git/WattmanGTK/WattmanGTK/GPU.py", line 70, in get_states
    self.pstate_clock.append(int(match.group(2)))
AttributeError: 'NoneType' object has no attribute 'group'

```

```
OD_SCLK:
 0: 800Mhz
 1: 2044Mhz
 OD_MCLK:
 1: 875MHz
 OD_VDDC_CURVE:
 0: 800MHz @ 696mV
 1: 1422MHz @ 803mV
 2: 2044MHz @ 1163mV
 OD_RANGE:
 SCLK:     800Mhz       2150Mhz
 MCLK:     625Mhz        950Mhz
 VDDC_CURVE_SCLK[0]:     800Mhz       2150Mhz
 VDDC_CURVE_VOLT[0]:     750mV        1200mV
 VDDC_CURVE_SCLK[1]:     800Mhz       2150Mhz
 VDDC_CURVE_VOLT[1]:     750mV        1200mV
 VDDC_CURVE_SCLK[2]:     800Mhz       2150Mhz
 VDDC_CURVE_VOLT[2]:     750mV        1200mV
```
