### ISSUE TITLE
backend_gtk3.py aise ImportError(exc)

### ISSUE THREAD

**Issue by Skeletonix** [BoukeHaarsma23/WattmanGTK#60]
Hello, 
I cannot run the WattmanGTK on openSuse Tumbleweed (KDE). The error is:

```
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(wattmanGTK:14439): Gdk-CRITICAL **: 19:41:41.819: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/matplotlib/backends/backend_gtk3.py", line 28, in <module>
    cursors.MOVE          : Gdk.Cursor.new(Gdk.CursorType.FLEUR),
TypeError: constructor returned NULL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/wattmanGTK", line 11, in <module>
    load_entry_point('WattmanGTK==0.0.1', 'console_scripts', 'wattmanGTK')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/wattman.py", line 16, in <module>
    from WattmanGTK.handler import Handler # handles GUI
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/handler.py", line 22, in <module>
    from WattmanGTK.plot import Plot
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/plot.py", line 20, in <module>
    from matplotlib.backends.backend_gtk3cairo import FigureCanvasGTK3Cairo as FigureCanvas # required for GTK3 integration
  File "/usr/lib64/python3.7/site-packages/matplotlib/backends/backend_gtk3cairo.py", line 1, in <module>
    from . import backend_cairo, backend_gtk3
  File "/usr/lib64/python3.7/site-packages/matplotlib/backends/backend_gtk3.py", line 37, in <module>
    raise ImportError(exc)
ImportError: constructor returned NULL

```
I've installed these packages:

* python3-cairo
* Python3-matplotlib
* Python3-matplotlib-gtk3
* Python3-matplotlib-cairo

Do you know what might be wrong?

**Comment by malasip** [comment]
Check that you have Python3-gi installed

**Comment by Skeletonix** [comment]
It looks like the Python3-gi  is not installed, but it is not in any 
openSuse repository.
