### ISSUE TITLE
Plotsignals.append error

### ISSUE THREAD

**Issue by yuceltoluyag** [BoukeHaarsma23/WattmanGTK#71]
5.1.14-arch1-1-ARCH #1 SMP PREEMPT Sat Jun 22 16:28:48 UTC 2019 x86_64 GNU/Linux
https://aur.archlinux.org/packages/wattman-gtk-git/  using this package
```
cat /sys/class/drm/card0/device/pp_dpm_sclk              
0: 300Mhz 
1: 751Mhz 
2: 1048Mhz *
3: 1130Mhz 
4: 1240Mhz 
5: 1309Mhz 
6: 1364Mhz 
7: 1411Mhz 
```

```
1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
lspci: Unable to load libkmod resources: error -12
03:00.0 uses amdgpu kernel driver
Searching for sysfs path...
/sys/devices/pci0000:00/0000:00:05.0/0000:03:00.0 belongs to 03:00.0 with symbolic link to /sys/class/drm/card0/device
Sysfs path found in /sys/devices/pci0000:00/0000:00:05.0/0000:03:00.0
amdgpu card found in /sys/class/hwmon/hwmon1 hwmon folder
Checking which device this hwmon path belongs to
/sys/class/hwmon/hwmon1 belongs to /sys/devices/pci0000:00/0000:00:05.0/0000:03:00.0 (ASUSTeK Computer Inc. Ellesmere [Radeon RX 470/480/570/570X/580/580X/590])
Found sensor freq1_label
Trying to read /sys/class/hwmon/hwmon1/freq1_label
Found sensor in0_input
Trying to read /sys/class/hwmon/hwmon1/in0_input
Found sensor fan1_min
Trying to read /sys/class/hwmon/hwmon1/fan1_min
Found sensor temp1_crit
Trying to read /sys/class/hwmon/hwmon1/temp1_crit
Found sensor pwm1_enable
Trying to read /sys/class/hwmon/hwmon1/pwm1_enable
Found sensor pwm1
Trying to read /sys/class/hwmon/hwmon1/pwm1
Found sensor temp1_crit_hyst
Trying to read /sys/class/hwmon/hwmon1/temp1_crit_hyst
Found sensor power1_cap_min
Trying to read /sys/class/hwmon/hwmon1/power1_cap_min
Found sensor fan1_enable
Trying to read /sys/class/hwmon/hwmon1/fan1_enable
Found sensor fan1_max
Trying to read /sys/class/hwmon/hwmon1/fan1_max
Found sensor freq2_label
Trying to read /sys/class/hwmon/hwmon1/freq2_label
Found sensor power1_cap
Trying to read /sys/class/hwmon/hwmon1/power1_cap
Found sensor pwm1_min
Trying to read /sys/class/hwmon/hwmon1/pwm1_min
Found sensor power1_average
Trying to read /sys/class/hwmon/hwmon1/power1_average
Found sensor freq1_input
Trying to read /sys/class/hwmon/hwmon1/freq1_input
Found sensor power1_cap_max
Trying to read /sys/class/hwmon/hwmon1/power1_cap_max
Found sensor fan1_input
Trying to read /sys/class/hwmon/hwmon1/fan1_input
Found sensor temp1_input
Trying to read /sys/class/hwmon/hwmon1/temp1_input
Found sensor pwm1_max
Trying to read /sys/class/hwmon/hwmon1/pwm1_max
Found sensor fan1_target
Trying to read /sys/class/hwmon/hwmon1/fan1_target
Found sensor freq2_input
Trying to read /sys/class/hwmon/hwmon1/freq2_input
Found sensor in0_label
Trying to read /sys/class/hwmon/hwmon1/in0_label
Reading clock states and limits.
Traceback (most recent call last):
  File "/usr/bin/wattmanGTK", line 11, in <module>
    load_entry_point('WattmanGTK==0.0.1', 'console_scripts', 'wattmanGTK')()
  File "/usr/lib/python3.7/site-packages/WattmanGTK/wattman.py", line 174, in main
    Plot0 = Handler0.init_plot(0, maxpoints, precision, linux_kernelmain, linux_kernelsub)
  File "/usr/lib/python3.7/site-packages/WattmanGTK/handler.py", line 72, in init_plot
    self.plot = Plot(self.builder, self.GPUs, maxpoints, precision, linux_kernelmain, linux_kernelsub)
  File "/usr/lib/python3.7/site-packages/WattmanGTK/plot.py", line 58, in __init__
    self.Plotsignals = self.init_signals(self.GPU)
  File "/usr/lib/python3.7/site-packages/WattmanGTK/plot.py", line 100, in init_signals
    self.add_available_signal(GPU.sensors, Plotsignals, hwmonpath=GPU.hwmonpath)
  File "/usr/lib/python3.7/site-packages/WattmanGTK/plot.py", line 156, in add_available_signal
    self.add_available_signal(value, Plotsignals, hwmonpath=hwmonpath, subsystem=subsystem, stop_recursion = stop_recursion)
  File "/usr/lib/python3.7/site-packages/WattmanGTK/plot.py", line 156, in add_available_signal
    self.add_available_signal(value, Plotsignals, hwmonpath=hwmonpath, subsystem=subsystem, stop_recursion = stop_recursion)
  File "/usr/lib/python3.7/site-packages/WattmanGTK/plot.py", line 151, in add_available_signal
    Plotsignals.append(Plotsignal(signallabel, subsystem_unit_color[subsystem]["unit"],
KeyError: ''

```

**Comment by electricsurge31** [comment]
I am getting a similar error as well.. any luck figuring this out?
5.1.8-1-MANJARO #1 SMP PREEMPT Sun Jun 9 20:44:14 UTC 2019 x86_64 GNU/Linux

`1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
1c:00.0 uses amdgpu kernel driver
Searching for sysfs path...
/sys/devices/pci0000:00/0000:00:03.1/0000:1c:00.0 belongs to 1c:00.0 with symbolic link to /sys/class/drm/card0/device
Sysfs path found in /sys/devices/pci0000:00/0000:00:03.1/0000:1c:00.0
amdgpu card found in /sys/class/hwmon/hwmon2 hwmon folder
Checking which device this hwmon path belongs to
/sys/class/hwmon/hwmon2 belongs to /sys/devices/pci0000:00/0000:00:03.1/0000:1c:00.0 (Tul Corporation / PowerColor Ellesmere [Radeon RX 470/480/570/570X/580/580X/590])
Found sensor freq1_label
Trying to read /sys/class/hwmon/hwmon2/freq1_label
Found sensor in0_input
Trying to read /sys/class/hwmon/hwmon2/in0_input
Found sensor fan1_min
Trying to read /sys/class/hwmon/hwmon2/fan1_min
Found sensor temp1_crit
Trying to read /sys/class/hwmon/hwmon2/temp1_crit
Found sensor pwm1_enable
Trying to read /sys/class/hwmon/hwmon2/pwm1_enable
Found sensor pwm1
Trying to read /sys/class/hwmon/hwmon2/pwm1
Found sensor temp1_crit_hyst
Trying to read /sys/class/hwmon/hwmon2/temp1_crit_hyst
Found sensor power1_cap_min
Trying to read /sys/class/hwmon/hwmon2/power1_cap_min
Found sensor fan1_enable
Trying to read /sys/class/hwmon/hwmon2/fan1_enable
Found sensor fan1_max
Trying to read /sys/class/hwmon/hwmon2/fan1_max
Found sensor freq2_label
Trying to read /sys/class/hwmon/hwmon2/freq2_label
Found sensor power1_cap
Trying to read /sys/class/hwmon/hwmon2/power1_cap
Found sensor pwm1_min
Trying to read /sys/class/hwmon/hwmon2/pwm1_min
Found sensor power1_average
Trying to read /sys/class/hwmon/hwmon2/power1_average
Found sensor freq1_input
Trying to read /sys/class/hwmon/hwmon2/freq1_input
Found sensor power1_cap_max
Trying to read /sys/class/hwmon/hwmon2/power1_cap_max
Found sensor fan1_input
Trying to read /sys/class/hwmon/hwmon2/fan1_input
Found sensor temp1_input
Trying to read /sys/class/hwmon/hwmon2/temp1_input
Found sensor pwm1_max
Trying to read /sys/class/hwmon/hwmon2/pwm1_max
Found sensor fan1_target
Trying to read /sys/class/hwmon/hwmon2/fan1_target
Found sensor freq2_input
Trying to read /sys/class/hwmon/hwmon2/freq2_input
Found sensor in0_label
Trying to read /sys/class/hwmon/hwmon2/in0_label
Reading clock states and limits.
Traceback (most recent call last):
  File "run.py", line 23, in <module>
    wattman.main()
  File "/home/electricsurge/system_setup/WattmanGTK/WattmanGTK/wattman.py", line 174, in main
    Plot0 = Handler0.init_plot(0, maxpoints, precision, linux_kernelmain, linux_kernelsub)
  File "/home/electricsurge/system_setup/WattmanGTK/WattmanGTK/handler.py", line 72, in init_plot
    self.plot = Plot(self.builder, self.GPUs, maxpoints, precision, linux_kernelmain, linux_kernelsub)
  File "/home/electricsurge/system_setup/WattmanGTK/WattmanGTK/plot.py", line 58, in __init__
    self.Plotsignals = self.init_signals(self.GPU)
  File "/home/electricsurge/system_setup/WattmanGTK/WattmanGTK/plot.py", line 100, in init_signals
    self.add_available_signal(GPU.sensors, Plotsignals, hwmonpath=GPU.hwmonpath)
  File "/home/electricsurge/system_setup/WattmanGTK/WattmanGTK/plot.py", line 156, in add_available_signal
    self.add_available_signal(value, Plotsignals, hwmonpath=hwmonpath, subsystem=subsystem, stop_recursion = stop_recursion)
  File "/home/electricsurge/system_setup/WattmanGTK/WattmanGTK/plot.py", line 156, in add_available_signal
    self.add_available_signal(value, Plotsignals, hwmonpath=hwmonpath, subsystem=subsystem, stop_recursion = stop_recursion)
  File "/home/electricsurge/system_setup/WattmanGTK/WattmanGTK/plot.py", line 151, in add_available_signal
    Plotsignals.append(Plotsignal(signallabel, subsystem_unit_color[subsystem]["unit"],
KeyError: ''`

**Comment by Benzhaomin** [comment]
Same issue as #66 

Fix here https://github.com/BoukeHaarsma23/WattmanGTK/issues/66#issuecomment-499446370

**Comment by kgguru** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/wattmanGTK", line 11, in <module>
    load_entry_point('WattmanGTK==0.0.1', 'console_scripts', 'wattmanGTK')()
  File "/usr/local/lib/python3.6/site-packages/WattmanGTK-0.0.1-py3.6.egg/WattmanGTK/wattman.py", line 158, in main
    card.get_states()
  File "/usr/local/lib/python3.6/site-packages/WattmanGTK-0.0.1-py3.6.egg/WattmanGTK/GPU.py", line 70, in get_states
    self.pstate_clock.append(int(match.group(2)))
AttributeError: 'NoneType' object has no attribute 'group'

what it means?
