### ISSUE TITLE
(Arch Linux) Wattman Doesn't Start

### ISSUE THREAD

**Issue by Nayr438** [BoukeHaarsma23/WattmanGTK#87]
Error Message 
```
Reading clock states and limits.
Traceback (most recent call last):
  File "run.py", line 23, in <module>
    wattman.main()
  File "/home/chris/WattmanGTK/WattmanGTK/wattman.py", line 158, in main
    card.get_states()
  File "/home/chris/WattmanGTK/WattmanGTK/GPU.py", line 70, in get_states
    self.pstate_clock.append(int(match.group(2)))
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by frhun** [comment]
Can confirm, same problem here.

**Comment by mikekenyon99** [comment]
Same here

**Comment by mluckau** [comment]
Same here on Manjaro
