### ISSUE TITLE
(Ubuntu) AttributeError: 'NoneType' object has no attribute 'group' when using run 

### ISSUE THREAD

**Issue by mikekenyon99** [BoukeHaarsma23/WattmanGTK#88]
When I use the command:

`python3 run.py`

it finds sensors and then gives me the following error:

```
Found sensor temp2_input
Trying to read /sys/class/hwmon/hwmon1/temp2_input
Reading clock states and limits.
Traceback (most recent call last):
  File "run.py", line 23, in <module>
    wattman.main()
  File "/home/mikekenyon/Documents/Linux/WattmanGTK-master/WattmanGTK/wattman.py", line 158, in main
    card.get_states()
  File "/home/mikekenyon/Documents/Linux/WattmanGTK-master/WattmanGTK/GPU.py", line 70, in get_states
    self.pstate_clock.append(int(match.group(2)))
AttributeError: 'NoneType' object has no attribute 'group'
```
![Screenshot from 2020-03-25 11-39-30](https://user-images.githubusercontent.com/42475982/77532907-b8514780-6e8d-11ea-9dd6-87ab54988ec1.png)

Thanks

Mike

**Comment by Hobbydos** [comment]
having the same issue on Ubuntu 20.04 and python 3.8.2

**Comment by alexforencich** [comment]
Seeing the same.  RX 5700 XT, Arch Linux, Python 3.8.3.

**Comment by jukie** [comment]
Same here. 5700xt, Arch, and Python 3.8

**Comment by xqqy** [comment]
same here RX5600xt, Ubuntu20.04 python3.8.2
