### ISSUE TITLE
Error during reading current states

### ISSUE THREAD

**Issue by stefanheijnen** [BoukeHaarsma23/WattmanGTK#9]
I get this error:
```
Error during reading current states, WattmanGTK will not be able to continue :(
Please check if "cat /sys/class/drm/card0/device/pp_od_clk_voltage" returns something useful
```
"cat /sys/class/drm/card0/device/pp_od_clk_voltage" returns nothing.

Is my system supported:

```
System:    Host: spin Kernel: 4.19.0-4-MANJARO x86_64 bits: 64 compiler: gcc v: 8.2.1 Desktop: KDE Plasma 5.14.2 
           Distro: Manjaro Linux 
Machine:   Type: Desktop Mobo: ASRock model: AB350 Gaming-ITX/ac serial: <root required> 
           UEFI [Legacy]: American Megatrends v: P4.70 date: 07/23/2018 
CPU:       Topology: Quad Core model: AMD Ryzen 5 2400G with Radeon Vega Graphics bits: 64 type: MT MCP arch: Zen 
           L2 cache: 2048 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 57513 
           Speed: 1913 MHz min/max: 1600/3600 MHz Core speeds (MHz): 1: 1913 2: 1537 3: 3167 4: 3565 5: 2430 
           6: 1818 7: 2470 8: 1653 
Graphics:  Device-1: AMD Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] driver: amdgpu v: kernel 
           bus ID: 38:00.0 
           Display: x11 server: X.Org 1.20.3 driver: amdgpu,ati unloaded: modesetting 
           resolution: 1920x1080~60Hz, 1680x1050~60Hz 
           OpenGL: renderer: AMD RAVEN (DRM 3.27.0 4.19.0-4-MANJARO LLVM 7.0.0) v: 4.5 Mesa 18.2.4 
           direct render: Yes 
Sensors:   System Temperatures: cpu: 35.0 C mobo: N/A gpu: amdgpu temp: 35 C 
           Fan Speeds (RPM): N/A 
```

**Comment by Haxk20** [comment]
I have Ryzen 5 2500U and pp_od_clk_voltage shows nothing for me too.
But when i change to my dedicated GPU it returns the output correctly. This is most likely bug in AMDGPU. But surely not bug in WattmanGTK.

**Comment by stefanheijnen** [comment]
@GloriousEggroll Yeah I've set video memory to 2GB, overclocked the memory to 3466. Oc'ing the CPU is not interesting for me.

For oc'ing your memory, this is a nice tool: https://www.overclock.net/forum/13-amd-general/1640919-ryzen-dram-calculator-1-1-0-beta-2-overclocking-dram-am4.html (Windows only, I've used it with an WinPE usb-stick.)

**Comment by BoukeHaarsma23** [comment]
Please check after 14e7de6d5708885716756bc744592cb6e444cb2d

**Comment by GloriousEggroll** [comment]
> @GloriousEggroll Yeah I've set video memory to 2GB, overclocked the memory to 3466. Oc'ing the CPU is not interesting for me.
> 
> For oc'ing your memory, this is a nice tool: https://www.overclock.net/forum/13-amd-general/1640919-ryzen-dram-calculator-1-1-0-beta-2-overclocking-dram-am4.html (Windows only, I've used it with an WinPE usb-stick.)

not the CPU, you can overclock the gpu core speed in the bios

**Comment by stefanheijnen** [comment]
After updating to the most recent version, installing and running it:

```
amdgpu card found in /sys/class/hwmon/hwmon1 hwmon folder
Error during reading current states, WattmanGTK will not be able to continue :(
Please check if "cat /sys/class/drm/card0/device/pp_od_clk_voltage" returns something useful
Cannot read file pp_od_clk_voltage, trying using pp_dpm_sclk and pp_dpm_mclk
Traceback (most recent call last):
  File "/usr/bin/wattmanGTK", line 11, in <module>
    load_entry_point('WattmanGTK==0.0.1', 'console_scripts', 'wattmanGTK')()
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/wattman.py", line 116, in main
    GPU0 = GPU(cards[int(cardnr)], linux_kernelmain, linux_kernelsub)
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/GPU.py", line 55, in __init__
    self.get_states()
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/GPU.py", line 110, in get_states
    self.power_cap_max = self.powersensors.read_attribute('_cap_max',True) / 1000000
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/GPU.py", line 31, in read_attribute
    return int(open(self.get_attribute_path(attribute,replace)).readline().rstrip())
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/hwmon/hwmon1/power1_cap_max'
```

```
 ls /sys/class/hwmon/hwmon1/ -ls
total 0
0 lrwxrwxrwx 1 root root    0 nov  9 10:11 device -> ../../../0000:38:00.0
0 -r--r--r-- 1 root root 4096 nov  9 10:11 fan1_input
0 -r--r--r-- 1 root root 4096 nov  9 10:11 in0_input
0 -r--r--r-- 1 root root 4096 nov  9 10:11 in0_label
0 -r--r--r-- 1 root root 4096 nov  9 10:11 in1_input
0 -r--r--r-- 1 root root 4096 nov  9 10:11 in1_label
0 -r--r--r-- 1 root root 4096 nov  9 10:09 name
0 drwxr-xr-x 2 root root    0 nov  9 10:11 power
0 -r--r--r-- 1 root root 4096 nov  9 10:11 power1_average
0 -rw-r--r-- 1 root root 4096 nov  9 10:11 pwm1
0 -rw-r--r-- 1 root root 4096 nov  9 10:11 pwm1_enable
0 -r--r--r-- 1 root root 4096 nov  9 10:11 pwm1_max
0 -r--r--r-- 1 root root 4096 nov  9 10:11 pwm1_min
0 lrwxrwxrwx 1 root root    0 nov  9 10:11 subsystem -> ../../../../../../class/hwmon
0 -r--r--r-- 1 root root 4096 nov  9 10:11 temp1_crit
0 -r--r--r-- 1 root root 4096 nov  9 10:11 temp1_crit_hyst
0 -r--r--r-- 1 root root 4096 nov  9 10:11 temp1_input
0 -rw-r--r-- 1 root root 4096 nov  9 10:11 uevent
```
cat /sys/class/drm/card0/device/pp_od_clk_voltage is still empty.

**Comment by BoukeHaarsma23** [comment]
d112ddc7470da3920a3a34702d526226d13ddebb should fix this for you.

Please also note that WattmanGTK will not be able to tune states, only % overclock due to the inability to read pp_od_clk_voltage.

**Comment by stefanheijnen** [comment]
And we continue with the next error:

amdgpu card found in /sys/class/hwmon/hwmon1 hwmon folder
Error during reading current states, WattmanGTK will not be able to continue :(
Please check if "cat /sys/class/drm/card0/device/pp_od_clk_voltage" returns something useful
Cannot read file pp_od_clk_voltage, trying using pp_dpm_sclk and pp_dpm_mclk
No power sensing

(wattmanGTK:22284): Gtk-WARNING **: 15:49:59.865: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(wattmanGTK:22284): Gtk-WARNING **: 15:49:59.865: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(wattmanGTK:22284): Gtk-WARNING **: 15:49:59.865: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version```


(wattmanGTK:22284): Gtk-WARNING **: 15:49:59.865: Theme parsing error: gtk.css:83:29: The style property GtkStatusbar:shadow-type is deprecated and shouldn't be used anymore. It will be removed in a future version
Traceback (most recent call last):
  File "/usr/bin/wattmanGTK", line 11, in <module>
    load_entry_point('WattmanGTK==0.0.1', 'console_scripts', 'wattmanGTK')()
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/wattman.py", line 131, in main
    Plot0 = Plot(builder, GPU0, maxpoints, precision, linux_kernelmain, linux_kernelsub)
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/plot.py", line 74, in __init__
    self.update_signals()
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/plot.py", line 138, in update_signals
    Plotsignal.retrieve_data(self.maxpoints)
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/plotsignal.py", line 41, in retrieve_data
    self.add_value(self.parser(self.sensorpath),maxpoints)
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/GPU.py", line 28, in read
    return int(open(self.path).readline().rstrip())
OSError: [Errno 22] Invalid argument
```

**Comment by BoukeHaarsma23** [comment]
Please switch to the debug-plot branch. It has extra debugging symbols in that function. See 41f1c11372ccd1fb478b6cc4a4ec0fe037205656

Now the program will spam your terminal with files it can not read. Which ones are those?

**Comment by BoukeHaarsma23** [comment]
If you have time, please let me know if the wattmangtk-next branch works for you!

**Comment by stefanheijnen** [comment]
> Please switch to the debug-plot branch. It has extra debugging symbols in that function. See [41f1c11](https://github.com/BoukeHaarsma23/WattmanGTK/commit/41f1c11372ccd1fb478b6cc4a4ec0fe037205656)
> 
> Now the program will spam your terminal with files it can not read. Which ones are those?

Am I missing a step? Because I get exactly the same output as on master.

```
git checkout debug-plot
sudo python3 setup.py install
```


> If you have time, please let me know if the wattmangtk-next branch works for you!

```
1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
38:00.0 uses amdgpu kernel driver
Searching for sysfs path...
/sys/devices/pci0000:00/0000:00:08.1/0000:38:00.0 belongs to 38:00.0 with symbolic link to /sys/class/drm/card0/device
Sysfs path found in /sys/devices/pci0000:00/0000:00:08.1/0000:38:00.0
amdgpu card found in /sys/class/hwmon/hwmon1 hwmon folder
Checking which device this hwmon path belongs to
/sys/class/hwmon/hwmon1 belongs to /sys/devices/pci0000:00/0000:00:08.1/0000:38:00.0 (Advanced Micro Devices, Inc. [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series])
Found sensor in1_label
Trying to read /sys/class/hwmon/hwmon1/in1_label
Found sensor in0_input
Trying to read /sys/class/hwmon/hwmon1/in0_input
Found sensor temp1_crit
Trying to read /sys/class/hwmon/hwmon1/temp1_crit
Found sensor pwm1_enable
Trying to read /sys/class/hwmon/hwmon1/pwm1_enable
Found sensor pwm1
Trying to read /sys/class/hwmon/hwmon1/pwm1
Found sensor temp1_crit_hyst
Trying to read /sys/class/hwmon/hwmon1/temp1_crit_hyst
Found sensor in1_input
Trying to read /sys/class/hwmon/hwmon1/in1_input
Found sensor pwm1_min
Trying to read /sys/class/hwmon/hwmon1/pwm1_min
Found sensor power1_average
Trying to read /sys/class/hwmon/hwmon1/power1_average
Found sensor fan1_input
Trying to read /sys/class/hwmon/hwmon1/fan1_input
Found sensor temp1_input
Trying to read /sys/class/hwmon/hwmon1/temp1_input
Found sensor pwm1_max
Trying to read /sys/class/hwmon/hwmon1/pwm1_max
Found sensor in0_label
Trying to read /sys/class/hwmon/hwmon1/in0_label
Cannot read file pp_od_clk_voltage, trying using pp_dpm_sclk and pp_dpm_mclk
Cannot do seperate overclocking via states, only by percentage!
No powercap sensors
No fan control
Traceback (most recent call last):
  File "/usr/bin/wattmanGTK", line 11, in <module>
    load_entry_point('WattmanGTK==0.0.1', 'console_scripts', 'wattmanGTK')()
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/wattman.py", line 141, in main
    Plot0 = Handler0.init_plot(0, maxpoints, precision, linux_kernelmain, linux_kernelsub)
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/handler.py", line 72, in init_plot
    self.plot = Plot(self.builder, self.GPUs, maxpoints, precision, linux_kernelmain, linux_kernelsub)
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/plot.py", line 70, in __init__
    self.update_signals()
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/plot.py", line 176, in update_signals
    self.signalstore[i][5]=str(np.around(convert_to_si(Plotsignal.unit, Plotsignal.get_min())[1], self.precision))
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/util.py", line 37, in convert_to_si
    return unit[0] + unit[2:], value / 1000
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

**Comment by BoukeHaarsma23** [comment]
let me know if it is fixed for you now. It did fix #37 which seems to be similar

**Comment by stefanheijnen** [comment]
```
1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
38:00.0 uses amdgpu kernel driver
Searching for sysfs path...
/sys/devices/pci0000:00/0000:00:08.1/0000:38:00.0 belongs to 38:00.0 with symbolic link to /sys/class/drm/card0/device
Sysfs path found in /sys/devices/pci0000:00/0000:00:08.1/0000:38:00.0
amdgpu card found in /sys/class/hwmon/hwmon1 hwmon folder
Checking which device this hwmon path belongs to
/sys/class/hwmon/hwmon1 belongs to /sys/devices/pci0000:00/0000:00:08.1/0000:38:00.0 (Advanced Micro Devices, Inc. [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series])
Found sensor in1_label
Trying to read /sys/class/hwmon/hwmon1/in1_label
Found sensor in0_input
Trying to read /sys/class/hwmon/hwmon1/in0_input
Cannot read /sys/class/hwmon/hwmon1/in0_input
Found sensor temp1_crit
Trying to read /sys/class/hwmon/hwmon1/temp1_crit
Found sensor pwm1_enable
Trying to read /sys/class/hwmon/hwmon1/pwm1_enable
Found sensor pwm1
Trying to read /sys/class/hwmon/hwmon1/pwm1
Found sensor temp1_crit_hyst
Trying to read /sys/class/hwmon/hwmon1/temp1_crit_hyst
Found sensor in1_input
Trying to read /sys/class/hwmon/hwmon1/in1_input
Cannot read /sys/class/hwmon/hwmon1/in1_input
Found sensor pwm1_min
Trying to read /sys/class/hwmon/hwmon1/pwm1_min
Found sensor power1_average
Trying to read /sys/class/hwmon/hwmon1/power1_average
Cannot read /sys/class/hwmon/hwmon1/power1_average
Found sensor fan1_input
Trying to read /sys/class/hwmon/hwmon1/fan1_input
Cannot read /sys/class/hwmon/hwmon1/fan1_input
Found sensor temp1_input
Trying to read /sys/class/hwmon/hwmon1/temp1_input
Found sensor pwm1_max
Trying to read /sys/class/hwmon/hwmon1/pwm1_max
Found sensor in0_label
Trying to read /sys/class/hwmon/hwmon1/in0_label
Reading clock states and limits.
Cannot read file pp_od_clk_voltage, trying using pp_dpm_sclk and pp_dpm_mclk
Cannot do seperate overclocking via states, only by percentage!
No powercap sensors
No fan control
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
AttributeError: 'NoneType' object has no attribute 'round'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/wattmanGTK", line 11, in <module>
    load_entry_point('WattmanGTK==0.0.1', 'console_scripts', 'wattmanGTK')()
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/wattman.py", line 141, in main
    Plot0 = Handler0.init_plot(0, maxpoints, precision, linux_kernelmain, linux_kernelsub)
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/handler.py", line 72, in init_plot
    self.plot = Plot(self.builder, self.GPUs, maxpoints, precision, linux_kernelmain, linux_kernelsub)
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/plot.py", line 70, in __init__
    self.update_signals()
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/plot.py", line 178, in update_signals
    self.signalstore[i][5]=str(np.around(convert_to_si(Plotsignal.unit, Plotsignal.get_min())[1], self.precision))
  File "/usr/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2800, in around
    return _wrapfunc(a, 'round', decimals=decimals, out=out)
  File "/usr/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/usr/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 41, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

```

**Comment by BoukeHaarsma23** [comment]
Let me know if you have any issues with this commit applied

**Comment by stefanheijnen** [comment]
It took some time, but WattmanGTK is running!

Mijn dank is groot!

**Comment by BoukeHaarsma23** [comment]
Can you post a screenshot with your setup? I'm interested in how it looks like on your setup. (Raven ridge APU)

**Comment by stefanheijnen** [comment]
![image](https://user-images.githubusercontent.com/1306331/48431034-00783a00-e771-11e8-9b57-642d27e430ca.png)

The strange thing is, the min, max, close buttons are on the right. I don't know if this is hardcoded in Wattman, or it is because I'm running a GTK app on KDE?

**Comment by BoukeHaarsma23** [comment]
I think that is indeed a GTK thing.

**Comment by txtsd** [comment]
Mine is similar. Can the GUI show less information on APUs since most of the all the interactive features are disabled anyway?

**Comment by BoukeHaarsma23** [comment]
Yes, from what I noticed is that the APU's don't do pstate overclocking. Therefore, I would recommend radeon-profile for those devices.
